create table users (
  id uuid primary key references auth.users(id) not null,
  email text unique not null,
  type text default 'USER' check(
    type in ('USER', 'ADMIN')
  ),
  avatar_url text not null,
  created_at timestamp default current_timestamp
);

create or replace function public.handle_new_user() returns trigger as $$
  begin
    if new.raw_user_meta_data->>'avatar_url' is null or new.raw_user_meta_data->>'avatar_url' = '' then
      new.raw_user_meta_data = jsonb_set(new.raw_user_meta_data, '{avatar_url}', to_jsonb('https://api.adorable.io/avatars/285/' || new.email || '.png'));
    end if;
    insert into public.users(id, email, avatar_url)
    values (new.id, new.email, new.raw_user_meta_data->>'avatar_url');
    return new;
  end;
$$ language plpgsql security definer;


create or replace trigger on_auth_user_created
  after insert on auth.users for each row
  execute procedure public.handle_new_user();


alter table users enable row level security;


create policy "Enable read access for all authenticated users"
  on users as permissive for select to authenticated
  using (true);


create table category (
  id bigint primary key generated by default as identity,
  created_at timestamp default current_timestamp,
  name text unique not null,
  imageUrl text not null,
  slug text not null,
  products int8[]
);


alter table category enable row level security;

create policy "Enable insert for admins only"
  on category for insert to authenticated
  with check (
    (SELECT type from public.users WHERE id = auth.uid()) = 'ADMIN'
  );

create policy "Enable update for admins only"
  on category for update to authenticated
  with check (
    (SELECT type from public.users WHERE id = auth.uid()) = 'ADMIN'
  );

create policy "Enable Delete from Admins only"
  on category for delete to authenticated
  using (
    (SELECT type from public.users WHERE id = auth.uid()) = 'ADMIN'
  );

create policy "Enable Read for all authenticated users"
  on category for delete to authenticated
  using (true);


create table product (
  id bigint primary key generated by default as identity,
  created_at timestamp default current_timestamp,
  title text unique not null,
  slug text unique not null,
  imagesUrl text[] not null,
  price int8 not null,
  heroImage text not null,
  category bigint references category(id) not null,
  maxQuantity int8 not null
);

alter table product enable row level security;


create policy "Enable read access for all users"
  on product as permissive for select to authenticated
  using (true);

create policy "Enable insert for admins only"
  on product for insert to authenticated
  with check (
    (SELECT type from public.users WHERE id = auth.uid()) = 'ADMIN'
  );

create policy "Enable update for admins only"
  on product for update to authenticated
  using (
    (SELECT type from public.users WHERE id = auth.uid()) = 'ADMIN'
  )
  with check (
    (SELECT type from public.users WHERE id = auth.uid()) = 'ADMIN'
  );

create policy "Enable delete for admins only"
  on product for delete to authenticated
  using (
    (SELECT type from public.users WHERE id = auth.uid()) = 'ADMIN'
  );